version: "2"

services:
  web:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - .:/code
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network

  php:
    image: php:fpm
    volumes:
      - .:/code
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
